import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    CHIEF = "CHIEF"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EMPLOYEE = "EMPLOYEE"
    INCOMING_DOC_OPERATOR = "INCOMING_DOC_OPERATOR"
    PERSONNEL_OFFICE = "PERSONNEL_OFFICE"
