import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    CHIEF = "CHIEF"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EMPLOYEE = "EMPLOYEE"
    INCOMING_DOC_OPERATOR = "INCOMING_DOC_OPERATOR"
    PERSONNEL_OFFICE = "PERSONNEL_OFFICE"


class DocumentType(str, enum.Enum):
    ORDER = "ORDER"
    INSTRUCTION = "INSTRUCTION"
    INCOMING_LETTER = "INCOMING_LETTER"
    RESOLUTION = "RESOLUTION"
    ORDER_EXTRACT = "ORDER_EXTRACT"


class DocumentStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ON_APPROVAL = "ON_APPROVAL"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    APPROVED = "APPROVED"
    ON_ACKNOWLEDGEMENT = "ON_ACKNOWLEDGEMENT"
    ACKNOWLEDGEMENT_COMPLETED = "ACKNOWLEDGEMENT_COMPLETED"
    REGISTERED = "REGISTERED"
    ARCHIVED = "ARCHIVED"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    UPLOADED = "UPLOADED"
    WAITING_RESOLUTION = "WAITING_RESOLUTION"
    RESOLUTION_CREATED = "RESOLUTION_CREATED"
    CLOSED = "CLOSED"
    CREATED = "CREATED"
    RECEIVED = "RECEIVED"


class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    WAITING = "WAITING"
    APPROVED = "APPROVED"
    RETURNED = "RETURNED"
    SKIPPED = "SKIPPED"


class AcknowledgementStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACKNOWLEDGED = "ACKNOWLEDGED"


class DocumentFileKind(str, enum.Enum):
    GENERATED_DOCX = "GENERATED_DOCX"
    GENERATED_PDF = "GENERATED_PDF"
    EXTRACT_DOCX = "EXTRACT_DOCX"
    EXTRACT_PDF = "EXTRACT_PDF"
